spellername = "Basque"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Basque spellchecker"
eu = "Euskara spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Basque, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
eu = "TRANSLATE: A spellchecker for Basque, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.eu"

[windows]
system_product_code = "{6C76FB57-479A-4548-883C-3FCB96B52959}_is1"
legacy_product_codes = [
    { value = "ED4821A4-31FA-44C5-B95B-2574827DDF37", kind = "nsis" },
    { value = "2E7FA9B6-62F9-4419-ADBF-B605B903A8A9", kind = "nsis" }
]
